Repository dasimagin/cart_pole, pull requests merged in 2021-08, with the labels that each got.

#6 simulator mvp
  cart_pole_v0.urdf
  position_control_demo.ipynb
  simulator.py
  state.py
Labels: simulator

#8 Add env interface
  README.md
  interface.py
Labels: simulator, hard, RL

#10 Simulator refactoring
  interface.py
  simulator.py
  state.py
Labels: simulator, RL

#5 Controller
  .clang-format
  .gitignore
  platformio.ini
  src/globals.cpp
  src/globals.h
  src/main.cpp
  src/protocol_processor.cpp
  src/protocol_processor.h
  src/stepper.cpp
  src/stepper.h
Labels: hard

#7 Py-Controller
  __init__.py
  device/__init__.py
  device/device.py
  device/tests/__init__.py
  device/tests/test_device.py
  device/wire_interface.py
  interface.py
  simulator.py
  util.py
Labels: hard
